print()
print("🎉 Boss-Quest abgeschlossen!")
print("🏆 Du hast den Daten-Kurator der unendlichen Schlüssel besiegt!")
print("⭐ Titel erhalten: Meister der Daten-Archive")
print()
print("🎊 GLÜCKWUNSCH! Du hast Woche 8 gemeistert!")
print("📚 Nächste Woche: JSON-Dateien und I/O!")