print()
print("🎉 Boss-Quest abgeschlossen!")
print("🏆 Du hast den Meister der unendlichen Wiederholungen besiegt!")
print("⭐ Titel erhalten: Meister der Zauberformeln")
print()
print("🎊 GLÜCKWUNSCH! Du hast Woche 5 gemeistert!")
print("📚 Nächste Woche: Listen (Listen erstellen, bearbeiten, durchsuchen)!")