print()
print('🎉 Boss Quest complete!')
print('🏆 You defeated the Stable Master of Infinite Archives!')
print('⭐ Title earned: Master of the Stable Archives')
print()
print('🎊 CONGRATULATIONS! You have mastered Week 9!')
print('📚 Next week: Object-Oriented Programming!')