print()
print("🎉 Boss Quest completed!")
print("🏆 You have defeated the Stable Master of the Infinite Archives!")
print("⭐ Title earned: Master of the Stable Archives")
print()
print("🎊 CONGRATULATIONS! You have mastered Week 8!")
print("📚 Next week: JSON files and I/O!")